defaults: &defaults
  twitter:
    clientId: "ZYMgTo6cIf96toPsGqiUnYGoj"
    clientSecret: "wpethwIoHZOZ6aii6Dh6tg4P2ymHvBAzkaJV6e9keFbwuEdkmh"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
